//------------------------------------------------------------------------------
// <auto-generated>
//	 This code was generated by a tool.
//	 Changes to this file may cause incorrect behavior and will be lost if
//	 the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// ReSharper disable All

using System;

namespace Assets.Editor.GameDevWare.TextTranform.Examples
{
	public static class BuildParameters
	{
		public static readonly DateTime Time = new DateTime(637541812378224912, DateTimeKind.Utc);
		public static readonly string UnityVersion = "2020.3.1f1";
		public static readonly string UnityPlatform = "WindowsEditor";
		public static readonly string OSVersion = "Microsoft Windows NT 10.0.19041.0";
		public static readonly string CurrentDirectory = "C:/Work/verticalTacticsClient/tacticsClient";
		public static readonly string UserName = "3dora";
		public static readonly bool Is64BitProcess = true;
	}
}
