//------------------------------------------------------------------------------
// <auto-generated>
//	 This code was generated by a tool.
//	 Changes to this file may cause incorrect behavior and will be lost if
//	 the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Collections.Generic;
using UI.UiCanvases;
using UniRx;
using UnityEngine;

namespace UI.UiCanvases
{
// ReSharper disable All
public partial class CanvasProvider
{
private readonly Dictionary<CanvasType, BaseUiCanvas> canvases = new();
        
public CanvasProvider() {
    Debug.Log("UiStateProvider created");
    CreateCanvases();
}

private void CreateCanvases() 
{
	var BackgroundUiCanvasPrefab = Resources.Load("BackgroundUiCanvas");
	var BackgroundUiCanvasCreated = GameObject.Instantiate(BackgroundUiCanvasPrefab) as GameObject;
	var BackgroundUiCanvas = BackgroundUiCanvasCreated.GetComponent<BackgroundUiCanvas>();

	BackgroundUiCanvas.Hide();

    canvases.Add(CanvasType.BackgroundUiCanvas, BackgroundUiCanvas);

	var LoadingUiCanvasPrefab = Resources.Load("LoadingUiCanvas");
	var LoadingUiCanvasCreated = GameObject.Instantiate(LoadingUiCanvasPrefab) as GameObject;
	var LoadingUiCanvas = LoadingUiCanvasCreated.GetComponent<LoadingUiCanvas>();

	LoadingUiCanvas.Hide();

    canvases.Add(CanvasType.LoadingUiCanvas, LoadingUiCanvas);

	var TopUiCanvasPrefab = Resources.Load("TopUiCanvas");
	var TopUiCanvasCreated = GameObject.Instantiate(TopUiCanvasPrefab) as GameObject;
	var TopUiCanvas = TopUiCanvasCreated.GetComponent<TopUiCanvas>();

	TopUiCanvas.Hide();

    canvases.Add(CanvasType.TopUiCanvas, TopUiCanvas);

	var LobbyUiCanvasPrefab = Resources.Load("LobbyUiCanvas");
	var LobbyUiCanvasCreated = GameObject.Instantiate(LobbyUiCanvasPrefab) as GameObject;
	var LobbyUiCanvas = LobbyUiCanvasCreated.GetComponent<LobbyUiCanvas>();

	LobbyUiCanvas.Hide();

    canvases.Add(CanvasType.LobbyUiCanvas, LobbyUiCanvas);

	var BottomUiCanvasPrefab = Resources.Load("BottomUiCanvas");
	var BottomUiCanvasCreated = GameObject.Instantiate(BottomUiCanvasPrefab) as GameObject;
	var BottomUiCanvas = BottomUiCanvasCreated.GetComponent<BottomUiCanvas>();

	BottomUiCanvas.Hide();

    canvases.Add(CanvasType.BottomUiCanvas, BottomUiCanvas);

	var SettingsUiCanvasPrefab = Resources.Load("SettingsUiCanvas");
	var SettingsUiCanvasCreated = GameObject.Instantiate(SettingsUiCanvasPrefab) as GameObject;
	var SettingsUiCanvas = SettingsUiCanvasCreated.GetComponent<SettingsUiCanvas>();

	SettingsUiCanvas.Hide();

    canvases.Add(CanvasType.SettingsUiCanvas, SettingsUiCanvas);

	var MatchUiCanvasPrefab = Resources.Load("MatchUiCanvas");
	var MatchUiCanvasCreated = GameObject.Instantiate(MatchUiCanvasPrefab) as GameObject;
	var MatchUiCanvas = MatchUiCanvasCreated.GetComponent<MatchUiCanvas>();

	MatchUiCanvas.Hide();

    canvases.Add(CanvasType.MatchUiCanvas, MatchUiCanvas);

	var ShopUiCanvasPrefab = Resources.Load("ShopUiCanvas");
	var ShopUiCanvasCreated = GameObject.Instantiate(ShopUiCanvasPrefab) as GameObject;
	var ShopUiCanvas = ShopUiCanvasCreated.GetComponent<ShopUiCanvas>();

	ShopUiCanvas.Hide();

    canvases.Add(CanvasType.ShopUiCanvas, ShopUiCanvas);

}
}

public enum CanvasType 
{
	BackgroundUiCanvas,
	LoadingUiCanvas,
	TopUiCanvas,
	LobbyUiCanvas,
	BottomUiCanvas,
	SettingsUiCanvas,
	MatchUiCanvas,
	ShopUiCanvas,
}

public partial class BackgroundUiCanvas : BaseUiCanvas
{
	private BackgroundUiCanvasIntent intent;
	public void SetData(BackgroundUiCanvasIntent intent)
	{
		this.intent = intent;
	}
}
public partial class LoadingUiCanvas : BaseUiCanvas
{
	private LoadingUiCanvasIntent intent;
	public void SetData(LoadingUiCanvasIntent intent)
	{
		this.intent = intent;
	}
}
public partial class TopUiCanvas : BaseUiCanvas
{
	private TopUiCanvasIntent intent;
	public void SetData(TopUiCanvasIntent intent)
	{
		this.intent = intent;
	}
}
public partial class LobbyUiCanvas : BaseUiCanvas
{
	private LobbyUiCanvasIntent intent;
	public void SetData(LobbyUiCanvasIntent intent)
	{
		this.intent = intent;
	}
}
public partial class BottomUiCanvas : BaseUiCanvas
{
	private BottomUiCanvasIntent intent;
	public void SetData(BottomUiCanvasIntent intent)
	{
		this.intent = intent;
	}
}
public partial class SettingsUiCanvas : BaseUiCanvas
{
	private SettingsUiCanvasIntent intent;
	public void SetData(SettingsUiCanvasIntent intent)
	{
		this.intent = intent;
	}
}
public partial class MatchUiCanvas : BaseUiCanvas
{
	private MatchUiCanvasIntent intent;
	public void SetData(MatchUiCanvasIntent intent)
	{
		this.intent = intent;
	}
}
public partial class ShopUiCanvas : BaseUiCanvas
{
	private ShopUiCanvasIntent intent;
	public void SetData(ShopUiCanvasIntent intent)
	{
		this.intent = intent;
	}
}

public partial class BackgroundUiCanvasIntent
{
    public Color color;
}
public partial class LoadingUiCanvasIntent
{
    public ReactiveProperty<int> progress;
}
public partial class TopUiCanvasIntent
{
    public ReactiveProperty<int> currencyAmount;
}
public partial class LobbyUiCanvasIntent
{
}
public partial class BottomUiCanvasIntent
{
}
public partial class SettingsUiCanvasIntent
{
}
public partial class MatchUiCanvasIntent
{
}
public partial class ShopUiCanvasIntent
{
}

}

